import os 
import torch

# Maximum time to burn
BURN_CYCLE = 3
ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# initial seed to generate spread, set and player policy seeds
SEED = 18740254

# sigma parameter for the action sets
SIGMA = 0.01

# number of episode repetitions 
EPISODE_REPS = 10

# number of games per participant
TRIALS_PER_PARTICIPANT = 10

# grid dimensions 
WIDTH = 10
HEIGHT = 10

FIELDS_PATH = 'fields' # Maps generated by generate_instances.py
AGENTS_PATH = f'agents'
# MODEL_PATH = f'outputs/model/double_dqn_final_150000episodes.pth'
MODEL_PATH = f'double_dqn_final_150000episodes.pth'
SPREADS_PATH = f'spreads'
REWARDS_PATH = f'rewards'



class GridConfig:
    def __init__(self, width, height, densities, fire_coords, spread_seed):
        """Initialize the grid configuration"""
        self.width = width
        self.height = height
        self.densities = densities
        self.fire_coords = fire_coords
        self.spread_seed = spread_seed
